name: Publish Python Package to PyPI

on:
  workflow_dispatch: # Allows manual trigger with 1 click

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4

    - name: Set Up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Compiling Tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build Software Package Modules
      run: python -m build

    - name: Publish Package to PyPI Index
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
